# Generated by Django 5.2.3 on 2025-07-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='port',
            field=models.IntegerField(default=554),
        ),
    ]
