# Generated by Django 5.2.3 on 2025-07-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamera', '0002_camera_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='chanel',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
