# Generated by Django 5.2.3 on 2025-07-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamera', '0003_camera_chanel'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='camera',
            name='youtube',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='camera',
            name='password',
            field=models.CharField(default='990507817a', max_length=50),
        ),
        migrations.AlterField(
            model_name='camera',
            name='username',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
