# Generated by Django 5.2.4 on 2025-07-08 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamera', '0004_camera_link_camera_youtube_alter_camera_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'verbose_name': 'Kamera', 'verbose_name_plural': 'Kameralar'},
        ),
        migrations.AddField(
            model_name='camera',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi?'),
        ),
        migrations.AlterField(
            model_name='bino',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Bino nomi'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='bino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kameralar', to='kamera.bino', verbose_name='Bino'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='chanel',
            field=models.CharField(default=101, max_length=100, verbose_name='Kanal raqami'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='ip',
            field=models.GenericIPAddressField(default='192.168.0.1', verbose_name='IP manzil'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='link',
            field=models.URLField(blank=True, max_length=500, verbose_name='YouTube havola'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Kamera nomi'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='password',
            field=models.CharField(default='990507817a', max_length=50, verbose_name='Parol'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='port',
            field=models.PositiveIntegerField(default=554, verbose_name='RTSP port'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='username',
            field=models.CharField(default='admin', max_length=50, verbose_name='Foydalanuvchi nomi'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='youtube',
            field=models.BooleanField(default=False, verbose_name="YouTube'ga uzatilsinmi?"),
        ),
    ]
