# Generated by Django 4.2.23 on 2025-07-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamera', '0004_camera_link_camera_youtube_alter_camera_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='sayt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='camera',
            name='sayt_link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='camera',
            name='chanel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='camera',
            name='ip',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
